spring.application.name=Taller2Practica1Application
server.port=8080

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?user=postgres.mifkyeysxdjuejcncmxr&password=Clique-Spool2-Browbeat
#spring.datasource.username=mkyong
#spring.datasource.password=password